### ISSUE TITLE
Crash on Android at application startup

### ISSUE THREAD

**Issue by ianwaldrop** [Kidoz-SDK/KIDOZ_Unity_SDK_Example#4]
Unity version: 5.5.1f1
Device: Samsung Galaxy S5

Other notes:
* No external SD Card present
* fresh install (all previous versions and variants of app uninstalled from device)

```
11-11 05:38:57.948: E/AndroidRuntime(30201): FATAL EXCEPTION: AsyncTask #3
11-11 05:38:57.948: E/AndroidRuntime(30201): Process: {REDACTED}, PID: 30201
11-11 05:38:57.948: E/AndroidRuntime(30201): java.lang.Error: FATAL EXCEPTION [AsyncTask #3]
11-11 05:38:57.948: E/AndroidRuntime(30201): Unity version     : 5.5.1f1
11-11 05:38:57.948: E/AndroidRuntime(30201): Device model      : samsung SM-G900V
11-11 05:38:57.948: E/AndroidRuntime(30201): Device fingerprint: Verizon/kltevzw/kltevzw:4.4.4/KTU84P/G900VVRU1ANI2:user/release-keys
11-11 05:38:57.948: E/AndroidRuntime(30201): Caused by: java.lang.RuntimeException: An error occured while executing doInBackground()
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.lang.Thread.run(Thread.java:841)
11-11 05:38:57.948: E/AndroidRuntime(30201): Caused by: java.lang.NoClassDefFoundError: android.support.v4.content.ContextCompat
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at com.kidoz.sdk.api.general.utils.SdkDeviceUtils.getInnerStoragePathIfPosible(SdkDeviceUtils.java:849)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at com.kidoz.sdk.api.general.assets_handling.AssetUtil.createAssetFile2(AssetUtil.java:118)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at com.kidoz.sdk.api.ui_views.video_unit.VideoUnitActivity$VideoUnitParserAsyncTask.doInBackground(VideoUnitActivity.java:587)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at com.kidoz.sdk.api.ui_views.video_unit.VideoUnitActivity$VideoUnitParserAsyncTask.doInBackground(VideoUnitActivity.java:531)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-11 05:38:57.948: E/AndroidRuntime(30201): 	... 3 more
```

**Comment by RinaKidoz** [comment]
Hi Ian,

Thanks for the message.

Please contact us at sdk@kidoz.net, so we can clarify few questions and assist you.

Thanks.

**Comment by ronen-k** [comment]
Issue reported on old version and already resolved.
