### ISSUE TITLE
android Build error

### ISSUE THREAD

**Issue by tree1891** [Kidoz-SDK/KIDOZ_Unity_SDK_Example#5]
```
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_162\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/Tools/android-sdk-windows\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files (x86)\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/Event;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/EventBulk;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/EventManager;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/EventManager$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/EventManager$2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/EventParameters;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/events/EventSyncAsyncTask;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/sdk/api/FeedButton;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/kidoz/sdk/api/FeedButton$1;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:313)
	at com.android.dx.command.dexer.Main.runDx(Main.java:291)
	at com.android.dx.command.dexer.Main.main(Main.java:247)
	at com.android.dx.command.Main.main(Main.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
	... 9 more
]
stdout[
processing archive D:\Work\Freelancer\Optiax\jp.alphabettouch_3\Temp\StagingArea\android-libraries\KidozSdk\libs\.\KidozSDK-Unity-0.8.3.2.jar...
processing com/kidoz/events/Event.class...
processing com/kidoz/events/EventBulk.class...
processing com/kidoz/events/EventManager.class...
```

**Comment by RinaKidoz** [comment]
Hello,

Thanks for your message.

Our technical team will look into this.

**Comment by tigerss** [comment]
Hi @tree1891, 

There is a new sdk version available so make sure you import it again

1. Can you check that Kidoz SDK is not added twice?
2. You can try to remove Kidoz SDK and add it again

**Comment by ronen-k** [comment]
Issue reported on old version and already resolved.
