### ISSUE TITLE
NumberFormatException on app startup

### ISSUE THREAD

**Issue by tree1891** [Kidoz-SDK/KIDOZ_Unity_SDK_Example#6]
```
Caused by: java.lang.NumberFormatException: For input string: "#ff33fc"
  at java.lang.Long.parseLong(Long.java:432)
  at android.graphics.Color.parseColor(Color.java:149)
  at com.kidoz.sdk.api.ui_views.one_item_view.OneItemFamilyView.applyStyleProperties(OneItemFamilyView.java:156)
  at com.kidoz.sdk.api.ui_views.one_item_view.OneItemFamilyView.<init>(OneItemFamilyView.java:112)
  at com.kidoz.sdk.api.ui_views.panel_view.FamilyPanelView.initInnerPanelView(FamilyPanelView.java:63)
  at com.kidoz.sdk.api.ui_views.panel_view.AbstractPanelView.initView(AbstractPanelView.java:186)
  at com.kidoz.sdk.api.ui_views.panel_view.AbstractPanelView.<init>(AbstractPanelView.java:120)
  at com.kidoz.sdk.api.ui_views.panel_view.FamilyPanelView.<init>(FamilyPanelView.java:46)
  at com.kidoz.sdk.api.PanelView.buildPanelView(PanelView.java:165)
  at com.kidoz.sdk.api.PanelView.access$200(PanelView.java:32)
  at com.kidoz.sdk.api.PanelView$2.onParseFinished(PanelView.java:144)
  at com.kidoz.sdk.api.general.assets_handling.AssetUtil$ParserAsyncTask.onPostExecute(AssetUtil.java:404)
  at com.kidoz.sdk.api.general.assets_handling.AssetUtil$ParserAsyncTask.onPostExecute(AssetUtil.java:307)
  at android.os.AsyncTask.finish(AsyncTask.java:660)
  at android.os.AsyncTask.-wrap1(AsyncTask.java)
  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6247)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by ronen-k** [comment]
Issue reported on old version and already resolved.
